module.exports = {
    VIEW_MAIN_CALENDAR: 'Ver calendario principal',
    VIEW_TIME_TREE_CALENDAR: 'Ver calendario Time Tree',
    CREATE_USERS: 'Alta de usuarios',
    VIEW_USERS: 'Ver usuarios',
    EDIT_USERS: 'Editar usuarios',
    DELETE_USERS: 'Eliminar usuarios',
    CREATE_CLIENTS: 'Alta de clientes',
    VIEW_CLIENTS: 'Ver clientes',
    EDIT_CLIENTS: 'Editar clientes',
    DELETE_CLIENTS: 'Eliminar clientes',
    EDIT_CABINS: 'Editar cabañas',
    CREATE_CABINS: 'Alta de cabañas',
    VIEW_CLEANING: 'Ver limpieza',
    VIEW_SERVICES: 'Ver servicios adicionales',
    CREATE_SERVICES: 'Alta de servicios adicionales',
    VIEW_RACK_SERVICES: 'Ver rack servicios',
    CREATE_RESERVATIONS: 'Crear reservaciones',
    DELETE_RESERVATIONS: 'Eliminar reservaciones',
    MODIFY_RESERVATION_STATUS: 'Editar estado de reserva',
    ADD_SERVICES_RESERVATION: 'Alta de servicios adicionales en reserva',
    VIEW_GLOBAL_UTILITIES: 'Ver utilidades globales',
    VIEW_PRICE_CALENDAR: 'Ver calendario de precios',
    EDIT_PRICE_CALENDAR: 'Editar calendario de precios',
    VIEW_BLOCK_CALENDAR: 'Ver calendario de bloqueos',
    EDIT_BLOCK_CALENDAR: 'Editar calendario de bloqueos',
    VIEW_LOGS: "Ver logs",
    VIEW_SURVEYS: "Ver encuestas",
    VIEW_MODIFY_SURVEY: "Editar encuestas",
    VIEW_RESERVATIONS_REPORT: "Ver reporte de reservaciones",
    VIEW_PAYMENTS_REPORT: "Ver reporte de pagos",
    ADD_PAYMENTS: "Alta de pagos",
    ADD_PRIVATE_NOTES: "Alta de notas privadas",

};