module.exports = {
    VIEW_MAIN_CALENDAR: 'Ver calendario principal',
    VIEW_TIME_TREE_CALENDAR: 'Ver calendario Time Tree',
    CREATE_USERS: 'Alta de usuarios',
    VIEW_USERS: 'Ver usuarios',
    EDIT_USERS: 'Editar usuarios',
    DELETE_USERS: 'Eliminar usuarios',
    CREATE_CLIENTS: 'Alta de clientes',
    VIEW_CLIENTS: 'Ver clientes',
    EDIT_CLIENTS: 'Editar clientes',
    DELETE_CLIENTS: 'Eliminar clientes',
    EDIT_CABINS: 'Editar cabañas',
    CREATE_CABINS: 'Alta de cabañas',
    VIEW_CLEANING: 'Ver limpieza',
    VIEW_SERVICES: 'Ver servicios adicionales',
    CREATE_SERVICES: 'Alta de servicios adicionales',
    VIEW_RACK_SERVICES: 'Ver rack servicios',
    CREATE_RESERVATIONS: 'Crear reservaciones',
    DELETE_RESERVATIONS: 'Eliminar reservaciones',
    MODIFY_RESERVATION_STATUS: 'Editar estado de reserva',
    ADD_SERVICES_RESERVATION: 'Alta de servicios adicionales en reserva',
    VIEW_GLOBAL_UTILITIES: 'Ver utilidades globales',
    VIEW_PRICE_CALENDAR: 'Ver calendario de precios',
    VIEW_BLOCK_CALENDAR: 'Ver/modificar calendario de bloqueos de fechas',
    VIEW_INVESTORS_CALENDAR: 'Ver calendario de bloqueos para inversionistas',
    VIEW_LOGS: "Ver logs",
    VIEW_SURVEY_ANSWERS: "Ver respuestas de encuestas",
    MODIFY_SURVEY: "Modificar encuesta",
    VIEW_RESERVATIONS_REPORT: "Ver reporte de reservaciones",
    VIEW_PAYMENTS_REPORT: "Ver reporte de pagos",
    ADD_PAYMENTS: "Alta de pagos",
    ADD_PRIVATE_NOTES: "Alta de notas privadas",
    
    // Permisos del módulo de Finanzas (Splitwise)
    VIEW_FINANCES: "Ver módulo de finanzas",
    MANAGE_ORGANIZATIONS: "Gestionar organizaciones (crear, editar, activar/desactivar)",
    VIEW_ORGANIZATIONS: "Ver organizaciones",
    CREATE_ACCOUNTS: "Crear cuentas",
    EDIT_ACCOUNTS: "Editar cuentas",
    DELETE_ACCOUNTS: "Eliminar cuentas",
    VIEW_ACCOUNTS: "Ver cuentas",
    ADD_ACCOUNT_PARTICIPANTS: "Agregar participantes a cuentas",
    REMOVE_ACCOUNT_PARTICIPANTS: "Eliminar participantes de cuentas",
    EDIT_TRANSACTIONS: "Editar transacciones",
    DELETE_TRANSACTIONS: "Eliminar transacciones",
    VIEW_TRANSACTIONS: "Ver transacciones",
    EXPORT_TRANSACTIONS: "Exportar transacciones a CSV",
    
    // Permisos del módulo de Cupones y Referidos
    CREATE_CUPONES: "Crear cupones",
    VIEW_CUPONES: "Ver cupones",
    EDIT_CUPONES: "Editar cupones",
    DELETE_CUPONES: "Eliminar cupones",
    EXPORT_CUPONES: "Exportar cupones a CSV",
    VIEW_REFERIDOS: "Ver referidos",
    MANAGE_REFERIDOS_CONFIG: "Gestionar configuración de referidos",

    // Permisos del módulo de Inventario/BOM
    VIEW_INVENTORY: "Ver inventario",
    MANAGE_INVENTORY: "Gestionar inventario",
    ADJUST_INVENTORY: "Ajustar inventario manual",
    VIEW_INVENTORY_DASHBOARD: "Ver dashboard de inventario",

};